name: Build and Test (macOS 15)
permissions: read-all
on:
  schedule:
    # daily at 3 AM
    - cron: "0 3 * * *"
  pull_request:
    types: [labeled]
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build-and-test:
    if: github.event_name != 'pull_request' || github.event.label.name == 'ci:macos'
    runs-on:
      labels: macos-15
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Cache bazel build artifacts
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7  # v5.0.2
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE.bzlmod', 'MODULE.bazel') }}-${{ hashFiles('bazel/import_llvm.bzl') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE.bzlmod', 'MODULE.bazel') }}-

      - name: Install rust
        run: brew install rust

      - name: Install OpenMP
        run: brew install libomp

      - name: Set OpenMP environment variables
        run: |
          echo "LDFLAGS=-L$(brew --prefix libomp)/lib" >> "$GITHUB_ENV"
          echo "CPPFLAGS=-I$(brew --prefix libomp)/include" >> "$GITHUB_ENV"

      - name: Bazel debug info
        run: |
          bazel cquery --output=starlark --starlark:expr="str(providers(target))" @bazel_tools//tools/cpp:current_cc_toolchain | sed 's/,/\n/g'

      - name: "Run `bazel build`"
        run: |
          bazel build --verbose_failures -c opt //...

      - name: "Run `bazel test`"
        run: |
           bazel test --verbose_failures -c opt //...
