name: Build and Test
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  Build And Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event."
      - run: echo "Running on OS ${{ runner.os }}"
      - run: echo "Checking out branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "Run `bazel build`"
        run: |
          bazel build //...
      - name: "Run `bazel test`"
        run: |
          bazel test //...
