name: Clang Matrix for Linux build
permissions: read-all
on:
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight (UTC) every Sunday
  workflow_dispatch:     # Allow manual triggering
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  # don't cache, run full build
  build-multi-clang:
    strategy:
      matrix:
        # since upgrading to C++20, only clang-17 and later are supported.
        clang-version: [17, 18, 19, 20, 21]
      fail-fast: false
    runs-on:
      labels: ubuntu-24.04-64core
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Install dependencies
        run: |
          ./.github/install_clang_version.sh ${{ matrix.clang-version }}

      - name: "Run `bazel build` with Clang ${{ matrix.clang-version }} + OpenMP"
        run: |
          bazel build --keep_going --incompatible_strict_action_env \
            -c opt //...
