name: update-lockfile
on:
  schedule:
    - cron: '00 1 * * 0'  # At 01:00 on Sundays.
  # allow this workflow to be manually run
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3

      - name: Run update lockfile
        run: bazel mod deps --lockfile_mode=update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0  # v8.1.0
        with:
          commit-message: "automated bazel lockfile update"
          title: "[deps] update bazel lockfile"
          labels: pull_ready, dependencies, bazel
