name: update-lockfile
on:
  schedule:
    - cron: '00 1 * * 0'  # At 01:00 on Sundays.
  # allow this workflow to be manually run
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Run update lockfile
        run: bazel mod deps --lockfile_mode=update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725  # v8
        with:
          commit-message: "automated bazel lockfile update"
          title: "[deps] update bazel lockfile"
          labels: pull_ready, dependencies, bazel
