name: Nightly release

permissions: read-all

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build-and-test:
    permissions:
      contents: write
      # Packages write permission required to update a release
      packages: write
    runs-on:
      labels: ubuntu-24.04-16core
    steps:
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3

      - name: Install dependencies
        run: |
          ./.github/install_clang_version.sh 19

      - name: "Run `bazel build`"
        run: |
          bazel build -c opt //tools:all

      - name: Ensure binaries can run
        shell: bash
        run: |
            bazel-bin/tools/heir-opt --help
            bazel-bin/tools/heir-translate --help
            bazel-bin/tools/heir-lsp --help
            [ -f bazel-bin/external/edu_berkeley_abc/abc ]

      - name: Delete previous existing nightly tag and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
            gh release view "nightly" && gh release delete "nightly" -y --cleanup-tag

      - name: GH Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b  # v2
        with:
          prerelease: true
          tag_name: nightly
          files: |
            bazel-bin/tools/heir-opt
            bazel-bin/tools/heir-translate
            bazel-bin/tools/heir-lsp
            bazel-bin/external/edu_berkeley_abc/abc
            lib/Transforms/YosysOptimizer/yosys/techmap.v
